In [ ]:
#EXPLORING TOKENS AND THEIR EMBEDDINGS

In [ ]:
#Downloading and Running a pretrained LLM from HuggingFace

In [1]:
from transformers import AutoModelForCausalLM, AutoTokenizer

# Load model and tokenizer
model = AutoModelForCausalLM.from_pretrained(
    "microsoft/Phi-3-mini-4k-instruct",
    device_map="cuda",
    torch_dtype="auto",
    trust_remote_code=False,
)
tokenizer = AutoTokenizer.from_pretrained("microsoft/Phi-3-mini-4k-instruct")

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json:   0%|          | 0.00/967 [00:00<?, ?B/s]

model.safetensors.index.json:   0%|          | 0.00/16.5k [00:00<?, ?B/s]

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

model-00002-of-00002.safetensors:   0%|          | 0.00/2.67G [00:00<?, ?B/s]

model-00001-of-00002.safetensors:   0%|          | 0.00/4.97G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/181 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/3.44k [00:00<?, ?B/s]

tokenizer.model:   0%|          | 0.00/500k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.94M [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/306 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/599 [00:00<?, ?B/s]

In [3]:
prompt = "Write an email to my collage HOD regarding my leave of absence.<|assistant|>"

# Tokenize the input prompt
input_ids = tokenizer(prompt, return_tensors="pt").input_ids.to("cuda")

# Generate the text
generation_output = model.generate(
  input_ids=input_ids,
  max_new_tokens=200
)

# Print the output
print(tokenizer.decode(generation_output[0]))

Write an email to my collage HOD regarding my leave of absence.<|assistant|> Subject: Request for Leave of Absence

Dear [College Head's Name],

I hope this email finds you well. I am writing to request a leave of absence from [start date] to [end date].

During this period, I will be dealing with some personal matters that require my undivided attention. I understand the importance of my studies and the impact my absence may have on my academic progress. Therefore, I have taken the necessary steps to ensure that my coursework and responsibilities are managed during my absence.

To minimize the impact on my studies, I have arranged for my coursework to be completed online and have communicated with my professors to ensure that I am up-to-date with the course material. I have also informed my academic advisor and the relevant department heads about my leave of absence and have provided them with a detailed plan for my return to campus.

I am committed to

In [4]:
print(input_ids)

tensor([[14350,   385,  4876,   304,   590,  5321,   482,   379, 13668, 11211,
           590,  5967,   310, 18070, 29889, 32001]], device='cuda:0')

In [5]:
for id in input_ids[0]:
   print(tokenizer.decode(id))

Write
an
email
to
my
coll
age
H
OD
regarding
my
leave
of
absence
.
<|assistant|>

In [6]:
generation_output

tensor([[14350,   385,  4876,   304,   590,  5321,   482,   379, 13668, 11211,
           590,  5967,   310, 18070, 29889, 32001,  3323,   622, 29901, 10729,
           363,   951,  1351,   310, 24650,   663,    13,    13, 29928,   799,
           518,  1625,  4424, 12252, 29915, 29879,  4408,  1402,    13,    13,
         29902,  4966,   445,  4876, 14061,   366,  1532, 29889,   306,   626,
          5007,   304,  2009,   263,  5967,   310, 18070,   515,   518,  2962,
          2635, 29962,   304,   518,   355,  2635,  1822,    13,    13, 29928,
          3864,   445,  3785, 29892,   306,   674,   367, 16743,   411,   777,
          7333, 13750,   393,  1996,   590,   563,   440,  2618,  8570, 29889,
           306,  2274,   278, 13500,   310,   590, 11898,   322,   278, 10879,
           590, 18070,  1122,   505,   373,   590, 21567,  6728, 29889,  7857,
         29892,   306,   505,  4586,   278,  5181,  6576,   304,  9801,   393,
           590,  3236,  1287,   322,  5544,   747,  9770,   526,  8745,  2645,
           590, 18070, 29889,    13,    13,  1762,  6260,   675,   278, 10879,
           373,   590, 11898, 29892,   306,   505, 21050,   363,   590,  3236,
          1287,   304,   367,  8676,  7395,   322,   505,  7212,   630,   411,
           590, 25718,   943,   304,  9801,   393,   306,   626,   701, 29899,
           517, 29899,  1256,   411,   278,  3236,  5518, 29889,   306,   505,
           884, 23388,   590, 21567,   594, 19188,   322,   278,  8018, 14311,
         15883,  1048,   590,  5967,   310, 18070,   322,   505,  4944,   963,
           411,   263, 13173,  3814,   363,   590,   736,   304, 24165, 29889,
            13,    13, 29902,   626, 19355,   304]], device='cuda:0')

In [8]:
print(tokenizer.decode(3323))
print(tokenizer.decode(622))
print(tokenizer.decode([3323, 622]))
print(tokenizer.decode(19188))

Sub
ject
Subject
visor

In [9]:
#Comparing Trained LLM Tokenizers

In [10]:
from transformers import AutoModelForCausalLM, AutoTokenizer

colors_list = [
    '102;194;165', '252;141;98', '141;160;203',
    '231;138;195', '166;216;84', '255;217;47'
]

def show_tokens(sentence, tokenizer_name):
    tokenizer = AutoTokenizer.from_pretrained(tokenizer_name)
    token_ids = tokenizer(sentence).input_ids
    for idx, t in enumerate(token_ids):
        print(
            f'\x1b[0;30;48;2;{colors_list[idx % len(colors_list)]}m' +
            tokenizer.decode(t) +
            '\x1b[0m',
            end=' '
        )

In [18]:
text = """The mass-energy equivalence is given by E = mc^2.
Python uses indentation: if x == 10: print("Hello") 🎉
中文测试 – let’s see how it handles this! 🤖"""

In [19]:
show_tokens(text, "bert-base-uncased")

[CLS] the mass - energy equivalence is given by e = mc ^ 2 . python uses ind ##entation : if x = = 10 : print ( " hello " ) [UNK] 中 文 [UNK] [UNK] – let ’ s see how it handles this ! [UNK] [SEP]

In [20]:
show_tokens(text, "bert-base-cased")

[CLS] The mass - energy e ##qui ##valence is given by E = m ##c ^ 2 . Python uses in ##dent ##ation : if x = = 10 : print ( " Hello " ) [UNK] 中 文 [UNK] [UNK] – let ’ s see how it handles this ! [UNK] [SEP]

In [21]:
show_tokens(text, "gpt2")

The  mass - energy  equival ence  is  given  by  E  =  mc ^ 2 .
 Python  uses  indent ation :  if  x  ==  10 :  print (" Hello ")  � � �
 中 � � � � � �  –  let � � s  see  how  it  handles  this !  � � �

In [22]:
show_tokens(text, "google/flan-t5-small")

The mass - energy  e qui val ence is given by E =  m c <unk> 2. Python uses in den tation :  if  x = = 10 : print ( " H ello ")  <unk>  <unk>  – let ’ s see how it handles this !  <unk> </s>

In [23]:
show_tokens(text, "facebook/galactica-1.3b")

The  mass - energy  equivalence  is  given  by  E   =  mc ^ 2 .
 Py thon  uses  indentation :  if  x   ==   1 0 :  print ( " H ello " )   � � � �
 � � � � � � � � � �  –  let ’ s  see  how  it  handles  this !   � � � �

In [24]:
show_tokens(text, "microsoft/Phi-3-mini-4k-instruct")

The mass - energy equivalence is given by E = m c ^ 2 .
 Python uses ind entation : if x ==  1 0 : print (" Hello ")  � � � �
 中 文 测 试 – let ’ s see how it handles this !  � � � �

In [25]:
#Contextualized Word Embeddings From a Language Model (Like BERT)

In [26]:
from transformers import AutoModel, AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("microsoft/deberta-base")
model = AutoModel.from_pretrained("microsoft/deberta-v3-xsmall")

tokens = tokenizer('Hello world', return_tensors='pt')
output = model(**tokens)[0]

tokenizer_config.json:   0%|          | 0.00/52.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/474 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/578 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/241M [00:00<?, ?B/s]

In [27]:
output.shape

torch.Size([1, 4, 384])

In [28]:
for token in tokens['input_ids'][0]:
    print(tokenizer.decode(token))

[CLS]
Hello
 world
[SEP]

In [29]:
output

tensor([[[-3.4816,  0.0861, -0.1819,  ..., -0.0612, -0.3911,  0.3017],
         [ 0.1898,  0.3208, -0.2315,  ...,  0.3714,  0.2478,  0.8048],
         [ 0.2071,  0.5036, -0.0485,  ...,  1.2175, -0.2292,  0.8582],
         [-3.4278,  0.0645, -0.1427,  ...,  0.0658, -0.4367,  0.3834]]],
       grad_fn=<NativeLayerNormBackward0>)

In [ ]:
#Text Embeddings

In [30]:
from sentence_transformers import SentenceTransformer
model = SentenceTransformer('sentence-transformers/all-mpnet-base-v2')

vector = model.encode("This is the best movie ever!")

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.4k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/571 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/438M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/363 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [31]:
vector.shape

(768,)

In [32]:
#Word Embeddings

In [5]:
pip install gensim

Collecting gensim
  Downloading gensim-4.3.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (8.1 kB)
Collecting numpy<2.0,>=1.18.5 (from gensim)
  Downloading numpy-1.26.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 4.4 MB/s eta 0:00:00
Collecting scipy<1.14.0,>=1.7.0 (from gensim)
  Downloading scipy-1.13.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (60 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.6/60.6 kB 4.5 MB/s eta 0:00:00
Requirement already satisfied: smart-open>=1.8.1 in /usr/local/lib/python3.11/dist-packages (from gensim) (7.1.0)
Requirement already satisfied: wrapt in /usr/local/lib/python3.11/dist-packages (from smart-open>=1.8.1->gensim) (1.17.2)
Downloading gensim-4.3.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (26.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 26.7/26.7 MB 88.3 MB/s eta 0:00:00
Downloading numpy-1.26.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.3/18.3 MB 120.7 MB/s eta 0:00:00
Downloading scipy-1.13.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (38.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 38.6/38.6 MB 18.1 MB/s eta 0:00:00
Installing collected packages: numpy, scipy, gensim
  Attempting uninstall: numpy
    Found existing installation: numpy 2.0.2
    Uninstalling numpy-2.0.2:
      Successfully uninstalled numpy-2.0.2
  Attempting uninstall: scipy
    Found existing installation: scipy 1.15.3
    Uninstalling scipy-1.15.3:
      Successfully uninstalled scipy-1.15.3
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
thinc 8.3.6 requires numpy<3.0.0,>=2.0.0, but you have numpy 1.26.4 which is incompatible.
tsfresh 0.21.0 requires scipy>=1.14.0; python_version >= "3.10", but you have scipy 1.13.1 which is incompatible.
Successfully installed gensim-4.3.3 numpy-1.26.4 scipy-1.13.1

In [2]:
import gensim.downloader as api
model = api.load("glove-wiki-gigaword-50")

[==================================================] 100.0% 66.0/66.0MB downloaded

In [3]:
model.most_similar([model['king']], topn=11)

[('king', 1.0000001192092896),
 ('prince', 0.8236179351806641),
 ('queen', 0.7839043140411377),
 ('ii', 0.7746230363845825),
 ('emperor', 0.7736247777938843),
 ('son', 0.766719400882721),
 ('uncle', 0.7627150416374207),
 ('kingdom', 0.7542161345481873),
 ('throne', 0.7539914846420288),
 ('brother', 0.7492411136627197),
 ('ruler', 0.7434253692626953)]

In [1]:
#Recommending songs by embeddings

In [2]:
import pandas as pd
from urllib import request

data = request.urlopen('https://storage.googleapis.com/maps-premium/dataset/yes_complete/train.txt')


lines = data.read().decode("utf-8").split('\n')[2:]
playlists = [s.rstrip().split() for s in lines if len(s.split()) > 1]

songs_file = request.urlopen('https://storage.googleapis.com/maps-premium/dataset/yes_complete/song_hash.txt')
songs_file = songs_file.read().decode("utf-8").split('\n')
songs = [s.rstrip().split('\t') for s in songs_file]
songs_df = pd.DataFrame(data=songs, columns = ['id', 'title', 'artist'])
songs_df = songs_df.set_index('id')

In [3]:
print( 'Playlist #1:\n ', playlists[0], '\n')
print( 'Playlist #2:\n ', playlists[1])

Playlist #1:
  ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31', '32', '33', '34', '35', '36', '37', '38', '39', '40', '41', '2', '42', '43', '44', '45', '46', '47', '48', '20', '49', '8', '50', '51', '52', '53', '54', '55', '56', '57', '25', '58', '59', '60', '61', '62', '3', '63', '64', '65', '66', '46', '47', '67', '2', '48', '68', '69', '70', '57', '50', '71', '72', '53', '73', '25', '74', '59', '20', '46', '75', '76', '77', '59', '20', '43']

Playlist #2:
  ['78', '79', '80', '3', '62', '81', '14', '82', '48', '83', '84', '17', '85', '86', '87', '88', '74', '89', '90', '91', '4', '73', '62', '92', '17', '53', '59', '93', '94', '51', '50', '27', '95', '48', '96', '97', '98', '99', '100', '57', '101', '102', '25', '103', '3', '104', '105', '106', '107', '47', '108', '109', '110', '111', '112', '113', '25', '63', '62', '114', '115', '84', '116', '117', '118', '119', '120', '121', '122', '123', '50', '70', '71', '124', '17', '85', '14', '82', '48', '125', '47', '46', '72', '53', '25', '73', '4', '126', '59', '74', '20', '43', '127', '128', '129', '13', '82', '48', '130', '131', '132', '133', '134', '135', '136', '137', '59', '46', '138', '43', '20', '139', '140', '73', '57', '70', '141', '3', '1', '74', '142', '143', '144', '145', '48', '13', '25', '146', '50', '147', '126', '59', '20', '148', '149', '150', '151', '152', '56', '153', '154', '155', '156', '157', '158', '159', '160', '161', '162', '163', '164', '165', '166', '167', '168', '169', '170', '171', '172', '173', '174', '175', '60', '176', '51', '177', '178', '179', '180', '181', '182', '183', '184', '185', '57', '186', '187', '188', '189', '190', '191', '46', '192', '193', '194', '195', '196', '197', '198', '25', '199', '200', '49', '201', '100', '202', '203', '204', '205', '206', '207', '32', '208', '209', '210']

In [4]:
from gensim.models import Word2Vec

# Train our Word2Vec model
model = Word2Vec(
    playlists, vector_size=32, window=20, negative=50, min_count=1, workers=4
)

In [5]:
song_id = 2172

# Ask the model for songs similar to song #2172
model.wv.most_similar(positive=str(song_id))

[('2849', 0.9986050128936768),
 ('3116', 0.9976984262466431),
 ('3119', 0.9956898093223572),
 ('3167', 0.9953632354736328),
 ('2976', 0.9951989054679871),
 ('6624', 0.9942456483840942),
 ('2640', 0.9941296577453613),
 ('3094', 0.9940915703773499),
 ('5586', 0.9940688610076904),
 ('1922', 0.993661105632782)]

In [6]:
print(songs_df.iloc[2172])

title     Fade To Black
artist        Metallica
Name: 2172 , dtype: object

In [7]:
import numpy as np

def print_recommendations(song_id):
    similar_songs = np.array(
        model.wv.most_similar(positive=str(song_id),topn=5)
    )[:,0]
    return  songs_df.iloc[similar_songs]

# Extract recommendations
print_recommendations(2172)

                              title         artist
id
2849               Run To The Hills    Iron Maiden
3116        Communication Breakdown   Led Zeppelin
3119   There's Only One Way To Rock    Sammy Hagar
3167                      Unchained      Van Halen
2976                   I Don't Know  Ozzy Osbourne

In [8]:
print_recommendations(2172)

                              title         artist
id
2849               Run To The Hills    Iron Maiden
3116        Communication Breakdown   Led Zeppelin
3119   There's Only One Way To Rock    Sammy Hagar
3167                      Unchained      Van Halen
2976                   I Don't Know  Ozzy Osbourne